blog/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.about_page, name='about'),
    path('blog/', views.BlogPage.as_view(), name='blog'),
    path('like/<slug:slug>', views.blog_post_like, name='post_like'),
    path('edit_comment/<int:comment_id>',
         views.edit_comment, name='edit_comment'),
    path('<slug:slug>/delete/<int:comment_id>/',
         views.delete_comment, name='delete_comment'),
    path('<slug:slug>/', views.blog_post_page, name='post'),
]

events/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('events/', views.EventsPage.as_view(), name='events'),
    path('<slug:slug>/', views.event_post_page, name='event_post'),
    path('like/<slug:slug>', views.event_post_like, name='event_post_like'),
    path('edit_comment/<int:comment_id>',
         views.edit_comment_event, name='edit'),
    path('<slug:slug>/delete/<int:comment_id>/',
         views.delete_comment_event, name='delete'),
]

sportbike/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls'), name='blog_urls'),
    path('accounts/', include('allauth.urls')),
    path('events/', include('events.urls')),
]

blog/models.py
"""
Database models for the blog app
& comments section.
"""

from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))

BIKE_CATEGORY = (
    ('standards', 'Standard'),
    ('sport', 'Sport'),
    ('sport-touring', 'Sport Touring'),
    ('touring', 'Touring'),
    ('cruiser', 'Cruiser'),
    ('off-road', 'Off Road'),
)


# Model made by help from "I think therefore I blog" walkthrough

class BlogPost(models.Model):
    """
    Database model for submitting a blog post
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    engine_cc = models.IntegerField(default=0, null=False, blank=False)
    brand = models.CharField(max_length=50, null=True, blank=True)
    model = models.CharField(max_length=50, null=True, blank=True)
    category = models.CharField(
        max_length=50, choices=BIKE_CATEGORY, null=False, blank=False,
        default='standards')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    featured_image = CloudinaryField('image', default='placeholder')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(User, related_name='blog_likes', blank=True)

    class Meta:
        """
        Displays blog posts in descending order
        """
        ordering = ['-created_on']

    def __str__(self):
        """
        Returns a string representation of an object
        """
        return self.title

    def number_of_likes(self):
        """
        Returns total number of post likes
        """
        return self.likes.count()


# Model used from "I think therefore I blog" walkthrough.

class BlogComment(models.Model):

    """
    Database model for creating a comment
    on a blog post
    """
    post = models.ForeignKey(
        BlogPost, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        """
        Order comments in ascending order
        """
        ordering = ['created_on']

    def __str__(self):
        """
        Display the comment as the comment text,
        and comment author name
        """
        return f"Comment {self.body} by {self.name}"

events/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


STATUS = ((0, "Draft"), (1, "Published"))


class EventPost(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    location = models.CharField(max_length=100)
    updated_on = models.DateTimeField(auto_now=True)
    description = models.TextField()
    featured_image = CloudinaryField('image', default='placeholder')
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='events_likes', blank=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()


class EventComment(models.Model):
    post = models.ForeignKey(
        EventPost, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

blog/forms.py
"""
Comments form, allowing users to
comment on blog posts
"""
from .models import BlogComment
from django import forms


class CommentForm(forms.ModelForm):
    """
    Which form fields should be populated
    to submit a comment
    """
    class Meta:
        model = BlogComment
        fields = ('body',)

events/forms.py
from .models import EventComment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = EventComment
        fields = ('body',)

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import BlogPost, BlogComment
from .forms import CommentForm

# about.html page view


def about_page(request):
    """
    View for about page.
    """
    return render(request, "about.html")

# Class used from "I think therefore I blog" walkthrough.


class BlogPage(generic.ListView):
    """
    View for blog page.
    """
    model = BlogPost
    queryset = BlogPost.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog.html'
    paginate_by = 6

# view used from PP4_masterclass blog


def blog_post_page(request, slug, *args, **kwargs):
    """
    A function-based view to view the detail of a post.
    Largely the same as the class-based, but we don't have
    different methods for GET and POST. Because it's not a
    class, all of the extra "self" stuff is removed too.

    Functionally, it's the same, but it is a bit clearer
    what's going on. To differentiate between request methods,
    we use request.method == "GET" or request.method == "POST"
    """

    queryset = BlogPost.objects.filter(status=1)
    post = get_object_or_404(queryset, slug=slug)
    comments = post.comments.filter(approved=True).order_by("-created_on")
    comment_count = post.comments.filter(approved=True).count()
    liked = False
    commented = False

    if post.likes.filter(id=request.user.id).exists():
        liked = True

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Comment awaiting moderation.')
        else:
            comment_form = CommentForm()
    else:
        comment_form = CommentForm()

    return render(
        request,
        "post.html",
        {
            "post": post,
            "comments": comments,
            "comment_count": comment_count,
            "liked": liked,
            "comment_form": comment_form
        },
    )

# view used from PP4_masterclass blog


def blog_post_like(request, slug, *args, **kwargs):
    """
    The view to update the likes. Although it should always be
    called using the POST method, we have still added some
    defensive programming to make sure.
    """
    post = get_object_or_404(BlogPost, slug=slug)

    if request.method == "POST" and request.user.is_authenticated:
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

    return HttpResponseRedirect(reverse('post', args=[slug]))

# delete comment view


def delete_comment(request, slug, comment_id, *args, **kwargs):
    comment = get_object_or_404(BlogComment, id=comment_id)
    comment.delete()
    return HttpResponseRedirect(reverse('post', kwargs={"slug": slug}))

# edit view comment


def edit_comment(request, comment_id, *args, **kwargs):
    comment = get_object_or_404(BlogComment, id=comment_id)

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST, instance=comment)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
            return redirect('blog')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Error updating comment!')
    else:
        comment_form = CommentForm(instance=comment)

    return render(request, 'edit_comment.html', {'comment_form': comment_form})

events/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import EventPost, EventComment
from .forms import CommentForm


class EventsPage(generic.ListView):

    model = EventPost
    queryset = EventPost.objects.filter(status=1).order_by('-created_on')
    template_name = 'events.html'
    paginate_by = 3


def event_post_page(request, slug, *args, **kwargs):

    queryset = EventPost.objects.filter(status=1)
    post = get_object_or_404(queryset, slug=slug)
    comments = post.comments.filter(approved=True).order_by("-created_on")
    comment_count = post.comments.filter(approved=True).count()
    liked = False
    commented = False

    if post.likes.filter(id=request.user.id).exists():
        liked = True

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Comment awaiting moderation.')
        else:
            comment_form = CommentForm()
    else:
        comment_form = CommentForm()

    return render(
        request,
        "eventpost.html",
        {
            "post": post,
            "comments": comments,
            "comment_count": comment_count,
            "liked": liked,
            "comment_form": comment_form
        },
    )

# view used from PP4_masterclass blog


def event_post_like(request, slug, *args, **kwargs):

    post = get_object_or_404(EventPost, slug=slug)

    if request.method == "POST" and request.user.is_authenticated:
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

    return HttpResponseRedirect(reverse('event_post', args=[slug]))

# delete comment view


def delete_comment_event(request, slug, comment_id, *args, **kwargs):
    comment = get_object_or_404(EventComment, id=comment_id)
    comment.delete()
    return HttpResponseRedirect(reverse('event_post', kwargs={"slug": slug}))

# edit view comment


def edit_comment_event(request, comment_id, *args, **kwargs):
    comment = get_object_or_404(EventComment, id=comment_id)

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST, instance=comment)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
            return redirect('events')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Error updating comment!')
    else:
        comment_form = CommentForm(instance=comment)

    return render(request, 'edit_comment.html', {'comment_form': comment_form})

templates/about.html
{% extends "base.html" %} 

{% block content %}

{% load static %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static "assets/img/kiss.jpg" %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>Welcome to Sport Bike Blog!</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Hey there, fellow riders and enthusiasts! I'm Luka, the adventurer 
                    behind the handlebars, and I'm thrilled to welcome you to my two-wheeled universe. 
                    This blog is not just about motorcycles; it's a celebration of the wind in our hair, 
                    the open road beneath our wheels, and the passion that fuels our love for all things motorcycling.</p>
                <p>Who am I?</p>
                <p>I'm not just a rider; I'm a storyteller on a steel horse, navigating the highways 
                    and byways of life. Born with a love for the unmistakable rumble of engines and
                    the freedom that comes with each twist of the throttle, my journey into the world of motorcycles has been nothing short of exhilarating.</p>
                <p>Why Motorcycles?</p>
                <p>For me, motorcycles aren't just a mode of transportation; they're a way of life.
                    Whether it's the adrenaline-pumping thrill of a spirited ride through winding 
                    mountain roads or the camaraderie forged at a dusty roadside diner, motorcycles
                    have woven themselves into the very fabric of my existence. Through this blog, 
                    I aim to share the joy, challenges, and profound moments that come with embracing the motorcycle lifestyle.</p>
                <p>What to Expect?</p>
                <p>Expect a blend of gripping ride tales, gear reviews, maintenance tips, and the occasional philosophical musings about 
                    life on two wheels. I'll be your guide through the vast landscape of motorcycle culture, exploring everything from classic cruisers to 
                    cutting-edge sportbikes.</p>
                <p>Join the Ride!</p>
                <p>This blog isn't just about my experiences; it's a community for riders from all walks of life. 
                    Share your stories, ask questions, and let's embark on this thrilling journey together. 
                    Whether you're a seasoned rider or someone contemplating their first bike, there's a place for you here.</p>
                <p>So, buckle up (or helmet on!), and let's explore the world of motorcycles one twist of the throttle at a time. 
                    The road awaits, and I can't wait to have you along for the ride!</p>
                <p>Ride safe,</p>
                <p>Luka
                </p>
            </div>
        </div>
    </div>
</main>

{%endblock%}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script
      src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"
      crossorigin="anonymous"
    ></script>
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <title>Sport Bike Blog</title>
  </head>
  <body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="mainNav">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'about'%}"
          >My own experience blog</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto py-4 py-lg-0">
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'about'%}"
                >About</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog'%}"
                >Blog</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'events'%}"
                >Events</a
              >
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{% url 'account_logout' %}"
                >Logout</a
              >
            </li>
            {% else %}
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{% url 'account_signup' %}"
                >Sign Up</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{% url 'account_login' %}"
                >Login</a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <!-- MESSAGES: Used from "I think therefore I blog" -->
    <div class="container">
      <div class="row">
        <div class="col-md-8 offset-md-2">
          {% for message in messages %}
          <div
            class="alert {{ message.tags }} alert-dismissible fade show"
            id="msg"
            role="alert"
          >
            {{ message | safe }}
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="alert"
              aria-label="Close"
            ></button>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>

    {% block content %} {% endblock %}

    <!-- Footer-->
    <footer class="border-top">
      <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a
                  href="https://twitter.com"
                  target="_blank"
                  rel="noopener"
                  aria-label="Visit our Twitter page (opens in a new tab)"
                >
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a
                  href="https://facebook.com"
                  target="_blank"
                  rel="noopener"
                  aria-label="Visit our Facebook page (opens in a new tab)"
                >
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a
                  href="https://github.com/LukaGajic2"
                  target="_blank"
                  rel="noopener"
                  aria-label="Visit my Github page (opens in a new tab)"
                >
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <div class="small text-center text-muted fst-italic">
              Project created for educational purposes only.
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Taken from "I think therefore I blog" -->
    <script>
      setTimeout(function () {
          let messages = document.getElementById('msg');
          let alert = new bootstrap.Alert(messages);
          alert.close();
      }, 2500);
    </script>
  </body>
</html>

templates/blog.html
{% extends "base.html" %} {% block content %} {% load static %}

<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('{% static 'assets/img/triumph.jpg' %}')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Sport Bike Blog</h1>
          <span class="subheading">A Blog Started by Luka</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Post preview-->
      <div class="post-preview">
        {% for post in blogpost_list %}
        <div class="image-container">
          {% if "placeholder" in post.featured_image.url %}
          <img
            class="card-img-top"
            src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg"
            alt="daughters kiss"
          />
          {% else %}
          <img
            class="card-img-top"
            src=" {{ post.featured_image.url }}"
            alt="bike image"
          />
          {% endif %}
          <div class="image-flash">
            <p class="author">Written by {{ post.author }}</p>
          </div>
        </div>
        <a href="{% url 'post' post.slug  %}" class="post-link">
          <h2 class="post-title">{{ post.title }}</h2>
          <h3 class="post-subtitle">
            {{ post.engine_cc }}cc {{ post.brand }} {{ post.model }}
          </h3>
        </a>

        <hr class="my-4" />
        <p class="card-text">
          <i class="far fa-heart"></i> {{ post.number_of_likes }}
        </p>
        <hr class="my-4" />
        {% if forloop.counter|divisibleby:3 %}
        <div class="post-preview">{% endif %} {% endfor %}</div>
      </div>
      <!-- Pagination code-->
      {% if is_paginated %}
      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li>
            <a
              href="?page={{ page_obj.previous_page_number }}"
              class="page-link"
              >&laquo; PREV
            </a>
          </li>
          {% endif %} {% if page_obj.has_next %}
          <li>
            <a href="?page={{ page_obj.next_page_number }}" class="page-link">
              NEXT &raquo;</a
            >
          </li>

          {% endif %}
        </ul>
      </nav>
      {% endif %}
    </div>
  </div>
</div>

{%endblock%}

templates/edit_comment.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}
{%load static%}
<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('{% static 'assets/img/triumph.jpg' %}')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Sport Bike Blog</h1>
          <span class="subheading">A Blog Started by Luka</span>
        </div>
      </div>
    </div>
  </div>
</header>
<body>
  <div class="row">
    <div class="col-md-4 card mb-4 mt-3">
      <div class="card-body">
        {% if user.is_authenticated %}

        <h3>Edit a comment:</h3>
        <p>Posting as: {{ user.username }}</p>
        <form id="commentForm" method="POST" style="margin-top: 1.3em">
          {% csrf_token %} {{ comment_form | crispy }}
          <button id="submitButton" type="submit" class="btn btn-signup btn-lg">
            Edit
          </button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</body>
{% endblock content %}

templates/events.html
{% extends "base.html" %} {% block content %} {% load static %}

<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('{% static 'assets/img/event.jpeg' %}')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Bike Events</h1>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Post preview-->
      <div class="post-preview">
        {% for post in eventpost_list %}
        <div class="image-container">
          {% if "placeholder" in post.featured_image.url %}
          <img
            class="card-img-top"
            src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg"
            alt="default image"
          />
          {% else %}
          <img
            class="card-img-top"
            src=" {{ post.featured_image.url }}"
            alt="event image"
          />
          {% endif %}
          <div class="image-flash">
            <p class="author">{{ post.location }}</p>
          </div>
        </div>
        <a href="{% url 'event_post' post.slug %}" class="post-link">
          <h2 class="post-title">{{ post.title }}</h2>
        </a>

        <hr class="my-4" />
        <p class="card-text">
          <i class="far fa-heart"></i> {{ post.number_of_likes }}
        </p>
        <hr class="my-4" />
        {% if forloop.counter|divisibleby:3 %}
        <div class="post-preview">{% endif %} {% endfor %}</div>
      </div>
      <!-- Pagination code-->
      {% if is_paginated %}
      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li>
            <a
              href="?page={{ page_obj.previous_page_number }}"
              class="page-link"
              >&laquo; PREV
            </a>
          </li>
          {% endif %} {% if page_obj.has_next %}
          <li>
            <a href="?page={{ page_obj.next_page_number }}" class="page-link">
              NEXT &raquo;</a
            >
          </li>

          {% endif %}
        </ul>
      </nav>
      {% endif %}
    </div>
  </div>
</div>

{%endblock%}